email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Ben Hager"
tagline: ""
description: "Follow <a href=\"https://micro.blog/benhager\">@benhager on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/benhager\">@benhager on Micro.blog</a>."
baseurl: ""
url: "http://hager.blog"
markdown: "kramdown"
username: "benhager"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Ben Hager"
name: "Ben Hager"
gravatar_hash: "2618ed4ba403bdaf8bad9b712e1784d1"
avatar: "https://www.gravatar.com/avatar/2618ed4ba403bdaf8bad9b712e1784d1?s=160"
full_name: "Ben Hager"
bio: ""
twitter_username: "_benhager"
github_username: "benhager"
instagram_username: "stscdr"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"